### ISSUE TITLE
Neutron on conrtoller gives issue in centos7

### ISSUE THREAD

**Issue by dilipsun** [congto/OpenStack-Mitaka-Scripts#10]
systemctl enable neutron-server.service neutron-linuxbridge-agent.service neutron-dhcp-agent.service neutron-metadata-agent.service neutron-l3-agent.service
Failed to execute operation: No such file or directory

Hi Congto ,

I am getting following error when i try with Centos 

change eth0 to enp0s3 and eth1 to enp0s8 in ipadd script--Worked

before ip echo "notify_only=0" > /etc/yum/pluginconf.d/search-disabled-repos.conf --worked

rm /var/lib/nova/nova.sqlite--before nova --removed this entry for script to work

All works till neutron where i have trouble.Any idea

**Comment by congto** [comment]
@dilipsun hmmm, You can please send your topology, i need more information
