### ISSUE TITLE
note-manila driver

### ISSUE THREAD

**Issue by ghost** [congto/OpenStack-Mitaka-Scripts#4]
```
- Có 2 lựa chọn khi cài manila
 - Có sử dụng drivier
 - Không sử dụng driver: Yêu cầu có Neutron, Nova
```

Theo như docs viết là with driver tức là việc cấu hình `Driver Handle Share Service  = True`  (Generic Driver) thì là sẽ sử dụng nova, neutron và cinder tạo ra instance mới (share server)

còn without driver sẽ sử dụng Backend bên ngoài không liên quan tới các service neutron, nova ví dụ như GlusterFS, LVM, ....

**Comment by congto** [comment]
@greatbn  Như vậy cách `without driver` thường được khoái hơn.

**Comment by ghost** [comment]
@congto theo a  khoái hơn là scalability và high availability đúng ko a?

**Comment by congto** [comment]
@greatbn anh đang nghĩ thế vì đơn giản là không phụ thuộc quá nhiều vào neutron, cinder. Lúc đó nếu anh có các máy vật lý ở ngoài chuyên làm share storage thì hay hơn.

Anw, để trả nghiệm thêm xem thế nào.

Vụ giữa các tenant khác nhau có thể dùng malina-share có thông tin ko em nhỉ ?

**Comment by ghost** [comment]
@congto  e nghĩ có thể là tạo ra nhiều backend và share-type (private) trên mỗi tenant. mỗi share-type này chỉ định trên 1 backend. Việc làm này là manual.
