### ISSUE TITLE
sed -i s/notify_only=1/notify_only=0/g /etc/yum/pluginconf.d/search-disabled-repos.conf fails

### ISSUE THREAD

**Issue by valenbb** [congto/OpenStack-Mitaka-Scripts#5]
sed -i s/notify_only=1/notify_only=0/g /etc/yum/pluginconf.d/search-disabled-repos.conf fails as the file does not exist.

Suggestion: File should be created if it is not there and if it exists skip to reboot phase.

**Comment by congto** [comment]
Hi @valenbb !

Thanks

If you install on RHEL 7.2, You need config follow me. On CentOS 7.2 no.

Anw, I am try again and report.

CongTO
